apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: resume-evaluator
  labels:
    app: backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: v1
    spec:
      containers:
      - name: backend
        image: resume-evaluator-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        # Explicit environment variables (matching docker-compose.yml)
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: resume-evaluator-config
              key: HOST
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: resume-evaluator-config
              key: PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: resume-evaluator-config
              key: ENVIRONMENT
        # Load .env file contents (matching env_file: ./backend/.env)
        envFrom:
        - secretRef:
            name: backend-env-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: resume-evaluator
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP