---
- name: Deploy Resume Evaluator App
  hosts: resume-evaluator
  become: yes
  vars:
    app_dir: /home/ec2-user/agentic-resume-evaluator
    branch: deployment
    backend_dir: "{{ app_dir }}/backend"
    frontend_dir: "{{ app_dir }}/frontend"
  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present

    - name: Ensure Node.js and Python3 are installed
      yum:
        name:
          - nodejs
          - npm
          - python3
          - python3-virtualenv
        state: present

    - name: Pull latest code
      git:
        repo: https://github.com/YasinSaleem/agentic-resume-evaluator.git
        dest: "{{ app_dir }}"
        version: "{{ branch }}"
        force: yes

    - name: Ensure pip is installed
      yum:
        name: python3-pip
        state: present

    - name: Setup backend virtualenv if not exists
      command: python3 -m virtualenv venv
      args:
        chdir: "{{ backend_dir }}"
        creates: "{{ backend_dir }}/venv"

    - name: Install backend requirements
      pip:
        requirements: "{{ backend_dir }}/requirements.txt"
        virtualenv: "{{ backend_dir }}/venv"

    - name: Install frontend dependencies
      npm:
        path: "{{ frontend_dir }}"
        production: yes

    - name: Build frontend
      command: npm run build
      args:
        chdir: "{{ frontend_dir }}"

    - name: Ensure PM2 is installed globally
      npm:
        name: pm2
        global: yes

    - name: Start backend with PM2 if not running
      command: pm2 start uvicorn --name resume-backend -- app.main:app --host 0.0.0.0 --port 8000
      args:
        chdir: "{{ backend_dir }}"
      ignore_errors: yes

    - name: Start frontend with PM2 if not running
      command: pm2 start npm --name resume-frontend -- run start
      args:
        chdir: "{{ frontend_dir }}"
      ignore_errors: yes

    - name: Restart all PM2 processes
      command: pm2 restart all
      ignore_errors: yes

    - name: Save PM2 process list for auto-resurrection
      command: pm2 save
